---
- name: Install ruby requirements
  become: yes
  apt:
    pkg:
      - libsqlite3-dev
      - ruby-dev
      - ruby
    state: present
    force_apt_get: yes

- name: Install Mailcatcher
  become: yes
  gem: name=mailcatcher state=latest user_install=no build_flags=conservative
  failed_when: false

- name: Add mailcatcher conf file
  become: yes
  copy: src=mailcatcher.conf dest=/etc/init/mailcatcher.conf

- name: Make sure Mailcatcher is not running
  command: pkill mailcatcher
  register: command_result
  failed_when: false
  changed_when: "command_result.rc == 0"

- name: Start Mailcatcher
  shell: mailcatcher --ip 0.0.0.0
  ignore_errors: yes