---
- name: Create Database ({{ projectname }})
  become: true
  # PostgreSQL will only allow users to login from the postgres account by default
  become_user: postgres
  postgresql_db: name={{ db_name }}

- name: Create DB User ({{ projectname }})
  become: true
  become_user: postgres
  postgresql_user: >
    name={{ db_user }}
    password={{ db_password }}
    state=present role_attr_flags=NOSUPERUSER,CREATEDB

- name: Provide user with DB permissions ({{ projectname }})
  become: true
  become_user: postgres
  postgresql_user: user={{ db_user }} db={{ db_name }} priv=ALL

- name: Create virtualenv
  command: "{{ python }} -m venv {{ virtualenv_path }}"
  become: yes
  become_user: vagrant
  args:
    creates: "{{ virtualenv_path }}"

- name: Upgrade setuptools and pip ({{ projectname }})
  pip:
    name:
      - setuptools
      - pip
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ python }}"

- name: Install requirements ({{ projectname }})
  pip:
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ python }}"
    requirements: "{{ project_root_path }}/requirements.txt"

- name: Install some dev tools ({{ projectname }})
  pip:
    name:
      - ipdb
      - ipython
      - django-extensions
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ python }}"

- name: Install .env file ({{ projectname }})
  template: src=env_{{ projectname}}.j2 dest="{{ project_root_path }}/{{ projectname }}/.env" force=no

- name: Django commands ({{ projectname }})
  django_manage: command={{ item }} app_path={{ project_root_path }} virtualenv={{ virtualenv_path }}
  with_items: "{{ django_commands }}"
  ignore_errors: yes

