---
- name: Update Apt Cache
  become: yes
  apt:
    pkg: python-apt
    update_cache: yes
    force_apt_get: yes

#- name: Add apt repository for python 3.7
#  become: true
#  apt_repository:
#    repo: ppa:deadsnakes/ppa
#    update_cache: yes
#
#- name: Install python3
#  become: true
#  apt: pkg=python3.7 state=present

#- name: Install python 3.7 dependencies
#  apt:
#    pkg:
#      - python3.7
#      - python3.7-dev
#      - python3.7-venv

- name: Install python3
  become: yes
  apt:
    pkg: python3
    state: present
    force_apt_get: yes

- name: Install python packages
  become: yes
  apt:
    pkg:
        - python-setuptools
        - python3-setuptools
        - python3-pip
        - python3-dev
        - memcached
    state: present
    force_apt_get: yes

- name: Install database packages
  become: yes
  apt:
    pkg:
      - postgresql-9.5
      - postgresql-contrib-9.5
      - postgresql-server-dev-9.5
      - libpq-dev # Required for Ansible to interact with postgres
      - python-psycopg2 # Required for Ansible to interact with postgres
    state: present
    force_apt_get: yes

- name: Install packages for pillow
  become: yes
  apt:
    pkg:
      - libjpeg-dev
      - zlib1g-dev
      - libpng12-dev
      - libtiff5-dev
      - libjpeg8-dev
      - libfreetype6-dev
      - libwebp-dev
    state: present
    force_apt_get: yes

- name: Install git
  become: yes
  apt:
    pkg: git
    state: present
    force_apt_get: yes

- name: Add vagrant user to www-data
  become: yes
  user: name=vagrant groups=www-data
  ignore_errors: yes #this user wont exist in live

- name: Install virtualenv
  become: yes
  pip: executable=pip3 name=virtualenv

- name: Allow password authentication for local socket users and allow connections other than localhost
  become: yes
  copy: src={{ item }} dest=/etc/postgresql/9.5/main/{{ item }} force=yes
  with_items:
    - pg_hba.conf
    - postgresql.conf
  notify:
      - Restart Postgres

- name: Ensure postgres running
  become: yes
  service: name=postgresql state=started

- name: Allow password authentication for local socket users
  become: yes
  copy: src=pg_hba.conf dest=/etc/postgresql/9.5/main/pg_hba.conf force=yes
  notify:
      - Restart Postgres

- name: Give vagrant user permission for venvs folder
  become: yes
  file: path=/src/venvs/ state=directory mode=0777 owner=vagrant recurse=no group=vagrant
