---
- hosts: all
  roles:
      - setup
      - {
          role: setup_project,
          projectname: pipsevents,
          runserver_alias: runserverpips,
          forwarded_port: 7000
        }
      - {
          role: setup_project,
          projectname: polefit,
          runserver_alias: runserverpf,
          forwarded_port: 7200
        }
      - {
          role: setup_project,
          projectname: flexibeast,
          runserver_alias: runserverfb,
          forwarded_port: 7100
        }
      - {
          role: setup_project,
          projectname: poleperformance,
          runserver_alias: runserverpp,
          forwarded_port: 7300
        }
#      - {
#          role: setup_project,
#          projectname: aliciaskeys,
#          runserver_alias: runserverak,
#          forwarded_port: 7400
#        }
      - {
          role: setup_project,
          projectname: freedom_of_flight,
          runserver_alias: runserverfof,
          forwarded_port: 7500
        }
      - mailcatcher
      - {
        role: deploy,
        projectname: pipsevents,
        db_name: "{{ pipsevents.db_name }}",
        db_user: "{{ pipsevents.db_user }}",
        db_password: "{{ pipsevents.db_password }}",
        secret_key: "{{ pipsevents.secret_key }}",
        email_host_password: "{{ pipsevents.email_host_password }}",
        default_studio_email: "{{ pipsevents.default_studio_email }}",
        default_paypal_email: "{{ pipsevents.default_paypal_email }}",
        simplecrypt_password: "{{ pipsevents.simplecrypt_password }}",
        mailchimp_user: "{{ pipsevents.mailchimp_user }}",
        mailchimp_secret: "{{ pipsevents.mailchimp_secret }}",
        mailchimp_list_id: "{{ pipsevents.mailchimp_list_id }}",
        mailchimp_webhook_secret: "{{ pipsevents.mailchimp_webhook_secret }}",
        django_commands: "{{ pipsevents.django_commands }}"
      }
      - {
        role: deploy,
        projectname: polefit,
        db_name: "{{ polefit.db_name }}",
        db_user: "{{ polefit.db_user }}",
        db_password: "{{ polefit.db_password }}",
        secret_key: "{{ polefit.secret_key }}",
        email_host_password: "{{ polefit.email_host_password }}",
        default_paypal_email: "{{ polefit.default_paypal_email }}",
        simplecrypt_password: "{{ polefit.simplecrypt_password }}",
        django_commands: "{{ polefit.django_commands }}"
      }
      - {
        role: deploy,
        projectname: flexibeast,
        db_name: "{{ flexibeast.db_name }}",
        db_user: "{{ flexibeast.db_user }}",
        db_password: "{{ flexibeast.db_password }}",
        secret_key: "{{ flexibeast.secret_key }}",
        email_host_password: "{{ flexibeast.email_host_password }}",
        default_studio_email: "{{ flexibeast.default_studio_email }}",
        django_commands: "{{ flexibeast.django_commands }}"
      }
      - {
        role: deploy,
        projectname: poleperformance,
        db_name: "{{ poleperformance.db_name }}",
        db_user: "{{ poleperformance.db_user }}",
        db_password: "{{ poleperformance.db_password }}",
        secret_key: "{{ poleperformance.secret_key }}",
        email_host_password: "{{ poleperformance.email_host_password }}",
        default_studio_email: "{{ poleperformance.default_studio_email }}",
        default_paypal_email: "{{ poleperformance.default_paypal_email }}",
        simplecrypt_password: "{{ poleperformance.simplecrypt_password }}",
        django_commands: "{{ poleperformance.django_commands }}"
      }
#      - {
#        role: deploy,
#        projectname: aliciaskeys,
#        db_name: "{{ aliciaskeys.db_name }}",
#        db_user: "{{ aliciaskeys.db_user }}",
#        db_password: "{{ aliciaskeys.db_password }}",
#        secret_key: "{{ aliciaskeys.secret_key }}",
#        email_host_password: "{{ aliciaskeys.email_host_password }}",
#        django_commands: "{{ aliciaskeys.django_commands }}"
#      }
      - {
        role: deploy,
        projectname: freedom_of_flight,
        db_name: "{{ freedom_of_flight.db_name }}",
        db_user: "{{ freedom_of_flight.db_user }}",
        db_password: "{{ freedom_of_flight.db_password }}",
        secret_key: "{{ freedom_of_flight.secret_key }}",
        email_host_password: "{{ freedom_of_flight.email_host_password }}",
        default_paypal_email: "{{ freedom_of_flight.default_paypal_email }}",
        paypal_identity_token: "{{ freedom_of_flight.paypal_identity_token }}",
        invoice_key: "{{ freedom_of_flight.invoice_key }}",
        django_commands: "{{ freedom_of_flight.django_commands }}"
      }
  vars_files:
   - vault.yaml
