---
- name: Add bashrc_extra file ({{ projectname }})
  become: yes
  template: src=bashrc_extra dest=/home/vagrant/.bashrc_extra_{{ projectname }}

- name: Add to bashrc file ({{ projectname }})
  become: yes
  lineinfile: >
    dest=/home/vagrant/.bashrc
    state=present
    backup=yes
    line='source .bashrc_extra_{{ projectname }}'

- name: Give vagrant user permission for log folder ({{ projectname }})
  become: yes
  file: path={{ log_path }} state=directory mode=0777 owner=vagrant recurse=yes group=vagrant
